project:
  type: website
  output-dir: docs

website:
  title: "Kiki's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ek-ku
      - icon: bluesky
        href: https://bsky.app/profile/evelinekiki.bsky.social
format:
  html:
    theme:
      - solar
      - brand
    css: styles.css

plugins:
  - mcanouil/quarto-iconify




