project:
  type: website
  output-dir: docs

plugins:
  - mcanouil/quarto-iconify

website:
  title: "Kiki's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ek-ku
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/evelinekiki.bsky.social
      - icon: linkedin
        href: https://linkedin.com/in/ekkuijjer
      - text: "{{< iconify academicons academia-square >}}"
        href: https://soton.academia.edu/EvelineKikiKuijjer
format:
  html:
    theme:
      - flat
      - brand
    css: styles.css






